import { NextRequest, NextResponse } from "next/server";
import puppeteer from "puppeteer";

export async function GET(request: NextRequest) {
  const key = request.nextUrl.searchParams.get("key");

  if (key !== process.env.DASHBOARD_ACCESS_KEY) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  try {
    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    const page = await browser.newPage();

    // Build the dashboard URL with the access key
    const protocol = process.env.NODE_ENV === "production" ? "https" : "http";
    const host = request.headers.get("host") || "localhost:3000";
    const dashboardUrl = `${protocol}://${host}/?key=${encodeURIComponent(key)}`;

    await page.goto(dashboardUrl, { waitUntil: "networkidle0", timeout: 30000 });

    // Wait for chart to render
    await page.waitForSelector(".recharts-responsive-container", { timeout: 15000 });
    // Give animations time to complete
    await new Promise((resolve) => setTimeout(resolve, 2000));

    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "20mm", right: "15mm", bottom: "20mm", left: "15mm" },
      displayHeaderFooter: true,
      headerTemplate: "<div></div>",
      footerTemplate: `
        <div style="width: 100%; text-align: center; font-size: 9px; color: #3F1E56; opacity: 0.5; font-family: Georgia, serif; padding: 0 20mm;">
          Report Generated by Revelation Inc. AI for Epic &nbsp;•&nbsp; <span class="date"></span>
        </div>
      `,
    });

    await browser.close();

    const today = new Date().toISOString().split("T")[0];

    return new NextResponse(Buffer.from(pdf), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="Epic-Channel-Report-${today}.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate PDF report" },
      { status: 500 }
    );
  }
}
